<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-08 01:29

import django.db.models.deletion
=======
# Generated by Django 5.2.4 on 2025-07-31 02:16

>>>>>>> e6b7f6858cc326b09854aa30769aa37e890f5214
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> e6b7f6858cc326b09854aa30769aa37e890f5214
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('publication_year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
=======
                ('author', models.CharField(max_length=100)),
>>>>>>> e6b7f6858cc326b09854aa30769aa37e890f5214
            ],
        ),
    ]
